apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: whisper
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: tiannaru/whisper
        imagePullPolicy: Always
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: mariadb+pymysql://root:changethislol@mariadb-service.whisper.svc.cluster.local:3306/app
        - name: FIRST_SUPERUSER
          value: todo@example.com
        - name: FIRST_SUPERUSER_PASSWORD
          value: changethislol
