apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: whisper
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: tiannaru/whisper
        env:
        - name: DOCKER_IMAGE_BACKEND
          value: tiannaru/whisper:latest
        - name: DOCKER_IMAGE_CELERYWORKER
          value: tiannaru/celery-worker:latest
        - name: DOMAIN
          value: tiannaru.xyz
